src/Entity/Service.php
<?php

namespace App\Entity;

use App\Repository\ServiceRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ServiceRepository::class)
 */
class Service
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $price;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_add;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_update;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture3;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture4;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture5;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDateAdd(): ?\DateTimeInterface
    {
        return $this->date_add;
    }

    public function setDateAdd(\DateTimeInterface $date_add): self
    {
        $this->date_add = $date_add;

        return $this;
    }

    public function getDateUpdate(): ?\DateTimeInterface
    {
        return $this->date_update;
    }

    public function setDateUpdate(?\DateTimeInterface $date_update): self
    {
        $this->date_update = $date_update;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getPicture2(): ?string
    {
        return $this->picture2;
    }

    public function setPicture2(?string $picture2): self
    {
        $this->picture2 = $picture2;

        return $this;
    }

    public function getPicture3(): ?string
    {
        return $this->picture3;
    }

    public function setPicture3(?string $picture3): self
    {
        $this->picture3 = $picture3;

        return $this;
    }

    public function getPicture4(): ?string
    {
        return $this->picture4;
    }

    public function setPicture4(?string $picture4): self
    {
        $this->picture4 = $picture4;

        return $this;
    }

    public function getPicture5(): ?string
    {
        return $this->picture5;
    }

    public function setPicture5(?string $picture5): self
    {
        $this->picture5 = $picture5;

        return $this;
    }
}

src/Form/ServiceType.php
<?php

// namespace App\Form;

// use App\Entity\Service;
// use Symfony\Component\Form\AbstractType;
// use Symfony\Component\Form\FormBuilderInterface;
// use Symfony\Component\OptionsResolver\OptionsResolver;

// class ServiceType extends AbstractType
// {
//     public function buildForm(FormBuilderInterface $builder, array $options): void
//     {
//         $builder
//             ->add('name')
//             ->add('description')
//             ->add('price')
//             ->add('date_add')
//             ->add('date_update')
//             ->add('picture')
//             ->add('picture2')
//             ->add('picture3')
//             ->add('picture4')
//             ->add('picture5')
//         ;
//     }

//     public function configureOptions(OptionsResolver $resolver): void
//     {
//         $resolver->setDefaults([
//             'data_class' => Service::class,
//         ]);
//     }
// }


namespace App\Form;

use App\Entity\Service;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Regex;

class ServiceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'required' => true,
                'label' => 'Nom',
                'attr' => ['class' => 'form-control']
            ])
            ->add('description', TextareaType::class, [
                'required' => false,
                'label' => 'Description',
                'attr' => ['class' => 'form-control']
            ])
            ->add('price', TextType::class, [
                'required' => true,
                'label' => 'Prix',
                'constraints' => [
                    new NotBlank(),
                    new Regex('/[0-9]{1,10}/')
                ],
                'attr' => ['class' => 'form-control']
            ])
            ->add('picture', FileType::class, [
                'label' => 'Image',
                'mapped' => false,
                'required' => false,
                'attr' => ['accept' => 'image/*', 'class' => 'form-control-file'],
                'data_class' => null
            ])
            ->add('picture2', FileType::class, [
                'label' => 'Image',
                'mapped' => false,
                'required' => false,
                'attr' => ['accept' => 'image/*', 'class' => 'form-control-file'],
                'data_class' => null
            ])
            ->add('picture3', FileType::class, [
                'label' => 'Image',
                'mapped' => false,
                'required' => false,
                'attr' => ['accept' => 'image/*', 'class' => 'form-control-file'],
                'data_class' => null
            ])
            ->add('picture4', FileType::class, [
                'label' => 'Image',
                'mapped' => false,
                'required' => false,
                'attr' => ['accept' => 'image/*', 'class' => 'form-control-file'],
                'data_class' => null
            ])
            ->add('picture5', FileType::class, [
                'label' => 'Image',
                'mapped' => false,
                'required' => false,
                'attr' => ['accept' => 'image/*', 'class' => 'form-control-file'],
                'data_class' => null
            ])
            ->add('date_add', HiddenType::class, ['mapped' => false, 'data_class' => null])
            ->add('date_update', HiddenType::class, ['mapped' => false, 'data_class' => null]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Service::class,
        ]);
    }
}

src/Controller/ServiceController.php
<?php

namespace App\Controller;

use App\Entity\Service;
use App\Form\ServiceType;
use App\Repository\ServiceRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/service")
 */
class ServiceController extends AbstractController
{
    /**
     * @Route("/", name="app_service_index", methods={"GET"})
     */
    public function index(ServiceRepository $serviceRepository): Response
    {
        return $this->render('service/index.html.twig', [
            'services' => $serviceRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_service_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ServiceRepository $serviceRepository, EntityManagerInterface $entityManager): Response
    {
        $service = new Service();
        $form = $this->createForm(ServiceType::class, $service);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
                $serviceRepository->add($service, true);

                $service->setDateAdd(new \DateTime());

                $aMimeTypes = array("image/gif", "image/jpeg", "image/jpg",
                "image/png", "image/x-png", "image/tiff");
                $objfichier = $request->files->get('service');
                $fichier = $objfichier['picture'];
                if (!empty($fichier)) {
                    if (in_array($fichier->getClientmimeType(), $aMimeTypes)) {
                        if ($fichier->move('assets/images/SERVICE/',
                            $fichier->getClientOriginalName())) {
                            $service->setPicture($fichier->getClientOriginalName());
                        }
                    }
                }

            $entityManager->persist($service); //insertion
            $entityManager->flush(); //exécute la requête
            $this->addFlash('success', 'Service est ajouté');

            return $this->redirectToRoute('app_service_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('service/new.html.twig', [
            'service' => $service,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_service_show", methods={"GET"})
     */
    public function show(Service $service): Response
    {
        return $this->render('service/show.html.twig', [
            'service' => $service,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_service_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Service $service, ServiceRepository $serviceRepository): Response
    {
        $form = $this->createForm(ServiceType::class, $service);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $serviceRepository->add($service, true);

            return $this->redirectToRoute('app_service_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('service/edit.html.twig', [
            'service' => $service,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_service_delete", methods={"POST"})
     */
    public function delete(Request $request, Service $service, ServiceRepository $serviceRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$service->getId(), $request->request->get('_token'))) {
            $serviceRepository->remove($service, true);
        }

        return $this->redirectToRoute('app_service_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/service/_delete_form.html.twig
<form method="post" action="{{ path('app_service_delete', {'id': service.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ service.id) }}">
    <button class="btn">Delete</button>
</form>

templates/service/_form.html.twig
{{ form_start(form) }}
    {# {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button> #}

    <div class="d-flex flex-wrap">
    <div class="col-lg-6 col-sm-12 px-5">
        {{ form_row(form.name) }} <br>
        {{ form_row(form.description) }}
        {{ form_row(form.price) }} <br>
    </div>
    <div class="col-lg-6 col-sm-12 px-5">
        {{ form_row(form.picture) }}
        {{ form_row(form.picture2) }}
        {{ form_row(form.picture3) }}
        {{ form_row(form.picture4) }}
        {{ form_row(form.picture5) }}
    </div>
</div>
<div class="text-center py-5">
    <button class="cart_button">{{ button_label|default('Enregistrer') }}</button>
</div>
{{ form_end(form) }}

templates/service/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Service{% endblock %}

{% block body %}
    <h1>Edit Service</h1>

    {# {{ include('service/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_service_index') }}">back to list</a>

    {{ include('service/_delete_form.html.twig') }} #}


    <img class="img-fluid pb-4" width="100px" src="/assets/images/SERVICE/{{ service.picture }}">
    <img class="img-fluid pb-4" width="100px" src="/assets/images/SERVICE/{{ service.picture2 }}">
    <img class="img-fluid pb-4" width="100px" src="/assets/images/SERVICE/{{ service.picture3 }}">
    <img class="img-fluid pb-4" width="100px" src="/assets/images/SERVICE/{{ service.picture4 }}">
    <img class="img-fluid pb-4" width="100px" src="/assets/images/SERVICE/{{ service.picture5 }}">

        {{ include('service/_form.html.twig', {'button_label': 'Update'}) }}

        <div class="container justify-content-between d-flex flex-wrap py-2">
            <a class="btn btn-secondary" href="{{ path('app_service_index') }}">Retour</a>
            <form method="post" action="{{ path('app_service_delete', {'id': service.id}) }}" onsubmit="return confirm('Êtes-vous sûr de bien vouloir supprimer cet élément?');">
                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ service.id) }}">
                <button class="btn btn-danger">Delete</button>
            </form>
        </div>
{% endblock %}

templates/service/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Service index{% endblock %}

{% block body %}
    <h1>Service index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Description</th>
                <th>Price</th>
                {# <th>Date_add</th>
                <th>Date_update</th> #}
                {# <th>Picture</th>
                <th>Picture2</th>
                <th>Picture3</th>
                <th>Picture4</th>
                <th>Picture5</th> #}
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for service in services %}
            <tr>
                <td>{{ service.id }}</td>
                <td>{{ service.name }}</td>
                <td>{{ service.description }}</td>
                <td>{{ service.price }}</td>
                {# <td>{{ service.dateAdd ? service.dateAdd|date('Y-m-d') : '' }}</td>
                <td>{{ service.dateUpdate ? service.dateUpdate|date('Y-m-d') : '' }}</td> #}
                {# <td>{{ service.picture }}</td>
                <td>{{ service.picture2 }}</td>
                <td>{{ service.picture3 }}</td>
                <td>{{ service.picture4 }}</td>
                <td>{{ service.picture5 }}</td> #}
                <td>
                    <a href="{{ path('app_service_show', {'id': service.id}) }}">show</a>
                    <a href="{{ path('app_service_edit', {'id': service.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_service_new') }}">Create new</a>
{% endblock %}

templates/service/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Service{% endblock %}

{% block body %}
    <h1>Create new Service</h1>

    {{ include('service/_form.html.twig') }}

    <a href="{{ path('app_service_index') }}">back to list</a>
{% endblock %}

templates/service/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Service{% endblock %}

{% block body %}
    <h1>Service</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ service.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ service.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ service.description }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ service.price }}</td>
            </tr>
            <tr>
                <th>Date_add</th>
                <td>{{ service.dateAdd ? service.dateAdd|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_update</th>
                <td>{{ service.dateUpdate ? service.dateUpdate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Picture</th>
                {# <td>{{ service.picture }}</td> #}
                <td><img class="img-fluid" width="100" src="/assets/images/SERVICE/{{ service.picture }}"></td>
            </tr>
            <tr>
                <th>Picture2</th>
                {# <td>{{ service.picture2 }}</td> #}
                <td><img class="img-fluid" width="100" src="/assets/images/SERVICE/{{ service.picture2 }}"></td>
            </tr>
            <tr>
                <th>Picture3</th>
                {# <td>{{ service.picture3 }}</td> #}
                <td><img class="img-fluid" width="100" src="/assets/images/SERVICE/{{ service.picture3 }}"></td>
            </tr>
            <tr>
                <th>Picture4</th>
                {# <td>{{ service.picture4 }}</td> #}
                <td><img class="img-fluid" width="100" src="/assets/images/SERVICE/{{ service.picture4 }}"></td>
            </tr>
            <tr>
                <th>Picture5</th>
                {# <td>{{ service.picture5 }}</td> #}
                <td><img class="img-fluid" width="100" src="/assets/images/SERVICE/{{ service.picture5 }}"></td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_service_index') }}">back to list</a>

    <a href="{{ path('app_service_edit', {'id': service.id}) }}">edit</a>

    {{ include('service/_delete_form.html.twig') }}
{% endblock %}